---
- hosts: all
  name: Diamond connects to Service (Graphite and Grafana)
  become: true

  pre_tasks:
    - name: Debug vars
      debug:
        msg: "{{ vars | to_json }}"

  roles:
    - connects_to_graphite
    - connects_to_grafana
