tosca_definitions_version: alien_dsl_2_0_0

metadata:
  template_name: org.ystia.monitoring.service.types.impl.Grafana
  template_author: Ystia
  template_version: 1.0.0

description: |
  Grafana monitoring service.

imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - yorc-docker-types:1.0.0
  - org.ystia.monitoring.service.types.pub:1.0.0

repositories:
  docker:
    url: https://hub.docker.com/
    type: docker

node_types:
  org.ystia.monitoring.service.impl.Grafana:
    derived_from: org.ystia.monitoring.service.pub.MonitoringService
    metadata:
      icon: /images/grafana.png
    attributes:
      web_ui_url: { concat: ["http://", get_attribute: [ SELF, http_endpoint, ip_address ], ":", get_attribute: [ SELF, http_endpoint, port ]]}
      data_collection_ip_address: { get_attribute: [ REQ_TARGET, graphite, data_collection_ip_address ] }
      data_collection_port: { get_attribute: [ REQ_TARGET, graphite, data_collection_port ] }
    requirements:
      - graphite:
          capability: org.ystia.monitoring.service.pub.HttpEndpoint
          relationship: org.ystia.monitoring.relationships.GrafanaConnectToGraphite
          occurrences: [0, UNBOUNDED]
    interfaces:
      Standard:
        start:
          inputs:
            GRAPHITE_URL: { get_attribute: [REQ_TARGET, graphite, web_ui_url] }
            GF_AUTH_ANONYMOUS_ENABLED: true
          implementation:
            file: laurentg/grafana
            repository: docker
            type: tosca.artifacts.Deployment.Image.Container.Docker

relationship_types:
  org.ystia.monitoring.relationships.GrafanaConnectToGraphite:
    derived_from: tosca.relationships.ConnectsTo
    properties:
      datasource_name:
        type: string
        required: true
        default: Graphite_DS
    valid_target_types: [ org.ystia.monitoring.service.pub.HttpEndpoint ]
