- name: Install packages
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Ubuntu - install Xrv and paraview
      apt:
        name:
          - Xrv
          - paraview
        state: present
        update_cache: yes
      register: apt_res
      retries: 3
      until: apt_res is success
      when: ansible_distribution == 'Ubuntu'
    - name: RedHat - install Xrv and paraview
      yum:
        enablerepo: xrv
        name:
          - Xrv
          - paraview
        state: present
        update_cache: yes
      when: ansible_os_family == 'RedHat'
    - name: Debian - install unzip and bzip2
      apt:
        name:
          - Xrv
          - paraview
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
